### ISSUE TITLE
Need help setting up Denoify

### ISSUE THREAD

**Issue by garronej** [contrawork/graphql-helix#1]
Hey @danielrearden, 
Nice project,

I saw you attempted to use `package.json -> denoify -> ports` with a pika URL.
Unfortunately only `deno.land/x` and `githubraw` url are supported by this method.

Here what you need is to write a custom replacer that will tell Denoify how to replace the graphQL imports.  

Do you need help with that?

Regards,

**Comment by danielrearden** [comment]
That would be amazing, @garronej 😍 Any help in getting this ported to deno would be greatly appreciated!

**Comment by garronej** [comment]
@danielrearden Ok it should be no problem, I will write the replacer for graphql... when I manage to free some time for opensource. :octocat:

**Comment by danielrearden** [comment]
@garronej I ended up writing the replacer myself. Closing this issue since we now officially have Deno support 🦕

**Comment by garronej** [comment]
Cool!

**Comment by garronej** [comment]
@danielrearden 
Sorry about that: 
![image](https://user-images.githubusercontent.com/6702424/97932540-9481a880-1d70-11eb-83d5-b29a3b36a2d1.png)
Denoify should not forward this import statement to your replacer...  

That said, I don't understand why you don't do that instead: 
![image](https://user-images.githubusercontent.com/6702424/97932665-e32f4280-1d70-11eb-9d3e-c89323ebe6d8.png)
