### ISSUE TITLE
lambda example

### ISSUE THREAD

**Issue by sibelius** [contrawork/graphql-helix#10]
Lamdba is more popular everyday

it would be good to have an example of aws lamdbda usand graphql-helix

**Comment by n1ru4l** [comment]
I guess subscription does not make sense with lambda. I don't even know whether multipart response streaming is supported via API gateway (I bet not). Because of that plain `graphql.js` might be enough for such a use case 🤔

**Comment by pauloedurezende** [comment]
You're totally right, @n1ru4l.

Unfortunately, multipart response streaming doesn't work on AWS Lambda and subscription still be able to use with WebSockets over AWS API Gateway.

[I created a project to demonstrate](https://github.com/pauloedurezende/playground-helix-serverless) what it would be like to work with GraphQL using Serverless Framework, I hope it can serve as inspiration for people looking for an example in this area.
