### ISSUE TITLE
Adding a resolver hook (for timing)

### ISSUE THREAD

**Issue by zachasme** [contrawork/graphql-helix#24]
Hi!

I'm trying to expand our logging to include resolver timings, similar to https://github.com/apollographql/apollo-tracing

Right now we have to wrap each resolver in a higher-order function that tracks and logs execution time. Is it possible to do this globally similar to the `contextFactory` function?

If not, is this something you would be interested in including if I make a pull request?

**Comment by n1ru4l** [comment]
@zachasme I guess stuff like that can be achieved by using the awesome graphql-tools. https://www.graphql-tools.com/docs/schema-wrapping

IMHO this is schema related stuff and should not be a concern of the server/transport implementation.

**Comment by zachasme** [comment]
That makes so much sense! Thank you for the links 👍🏿

**Comment by yaacovCR** [comment]
Better off using mapSchema from Utils package to help wrap all resolvers, wrapSchema, will actually delegate entire query to an inner schema which is not what you want
