### ISSUE TITLE
Bundle size increase in v1.1.0 because of inlining graphiql

### ISSUE THREAD

**Issue by kamilkisiela** [contrawork/graphql-helix#26]
@danielrearden hello
https://github.com/contrawork/graphql-helix/commit/a234865893a2c29730acceeac597cd3a44165be4 this change adds 1mb to overall bundle size https://unpkg.com/browse/graphql-helix@1.1.0/dist/

**Comment by kamilkisiela** [comment]
Not sure if it's expected so I'm just leaving it here as an issue.

**Comment by orefalo** [comment]
I personally use altair, much clearer UI

**Comment by danielrearden** [comment]
This is to be expected. I think https://github.com/contrawork/graphql-helix/issues/9 will address this in the sense that the entire `renderGraphiQL` function will live in its own package separate from the core functionality.
