### ISSUE TITLE
GraphiQL does not work with helmet on

### ISSUE THREAD

**Issue by tvvignesh** [contrawork/graphql-helix#4]
Hi. I was trying to get GraphiQL to work but it got blocked with Content Security Policy errors as seen below:

<img width="695" alt="1" src="https://user-images.githubusercontent.com/1165845/98834810-a4327880-2465-11eb-8c87-1b76fb800f1a.png">

I disabled `fastify-helmet` and was able to get it working properly. Am I missing some config here?

There are similar issues, but with playground though: https://github.com/graphql/graphql-playground/issues/1283#issuecomment-703631091

I guess its better to use local js files with GraphiQL rather than files from the CDN (I may be wrong here). Thanks.

**Comment by n1ru4l** [comment]
> I guess its better to use local js files with GraphiQL rather than files from the CDN (I may be wrong here). Thanks.

The only way that would be reliable for all use-cases would be to inline all the js code into HTML :D

**Comment by tvvignesh** [comment]
Well, that would work too considering people are not going to be frequently reloading GraphiQL but just changing the operations within. So, I guess as long as the security factors is met, and it works, I guess there should not be any issue.

Wondering how others are doing this though.

**Comment by n1ru4l** [comment]
I actually talked about this a few years ago with the apollo team for embedding custom GraphiQL with tracing visualization inside apollo-server and we decided to do it, however, eventually, they changed the descision to go with graphql-playground and ditched the idea of inlining the code.

**Comment by tvvignesh** [comment]
@n1ru4l Hmm. I guess now that Playground is getting merged with GraphiQL, I guess, we might have to go with the approach with GraphiQL is taking. Wanted to see how `express-graphql` is doing it and noticed this: https://github.com/graphql/express-graphql/blob/master/src/renderGraphiQL.ts#L82

Looks like they are bundling and loading files statically after all. (Haven't tested it though)

**Comment by danielrearden** [comment]
Yes I am considering a similar approach for `renderGraphiQL` although it wouldn't use that transform.

**Comment by danielrearden** [comment]
@tvvignesh As of version 1.0.0, you can pass a `nonce` value to `renderGraphiQL`. I've also added a CSP example [here](https://github.com/contrawork/graphql-helix/tree/master/examples/csp) that shows how to integrate helmet.

**Comment by tvvignesh** [comment]
@danielrearden Thanks. Will try it out right away.

**Comment by tvvignesh** [comment]
Stuck now, because of this issue with `fastify-helmet`: https://github.com/fastify/fastify-helmet/issues/89#issuecomment-692117587

Moving to helmet to get this to work.

**Comment by tvvignesh** [comment]
@danielrearden Tried with `helmet` and Fastify. And it works well if `nonce` is added. Thanks.

**Comment by tvvignesh** [comment]
Btw, though this is not a big deal, looks like its throwing a 404 for the sourcemap:

<img width="957" alt="1" src="https://user-images.githubusercontent.com/1165845/100215241-c5e83100-2f36-11eb-8de7-d9e134613708.png">

**Comment by danielrearden** [comment]
Yup, it's on my list. Thanks!

**Comment by danielehrhardt** [comment]
> Yup, it's on my list. Thanks!

Ping :)
