### ISSUE TITLE
How to disable introspection for production?

### ISSUE THREAD

**Issue by wanton7** [contrawork/graphql-helix#50]
I would like to disable introspection for production environment. Is it possible with graphql-helix?

**Comment by orefalo** [comment]
same issue

**Comment by dotansimha** [comment]
You can either modify the `validationRules` and use `NoSchemaIntrospectionCustomRule` in addition to the default set of rules:

```
import { specifiedRules, NoSchemaIntrospectionCustomRule } from 'graphql';

// ... 

processRequest({
  // ...
  validationRules: [...specifiedRules, NoSchemaIntrospectionCustomRule]
})
```

Or, you can use `envelop` (https://github.com/dotansimha/envelop/) and configure it using the plugin (https://www.envelop.dev/plugins/use-disable-introspection)
